apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-test-cr
rules:
- apiGroups:
  - kubedb.com
  - catalog.kubedb.com
  - schema.kubedb.com
  - stash.appscode.com
  - repositories.stash.appscode.com
  - kubevault.com
  - engine.kubevault.com
  - batch
  - appcatalog.appscode.com
  - ""
  resources:
  - '*'
  verbs:
  - '*'