apiVersion: schema.kubedb.com/v1alpha1
kind: MongoDBDatabase
metadata:
  name: mongodbdatabase-sample
  namespace: dev
spec:
  database_ref:
    dbref_name: "mongodb"
    dbref_namespace: "db"
  vault_ref:
    vaultref_name: "vault"
    vaultref_namespace: "demo"
  database_schema:
    dbschema_name: "mydb"
  subjects:
    - subject_name: "sa_name"
      subject_kind:
        apiVersion: "v1"
        kind: "ServiceAccount"
      subject_namespace: "dev"
  init:
    initialized: false
    waitForInitialRestore: true
    script:
      script_path: "/etc/config"
      volume_source:
        configMap:
          name: "test-cm"
    pod_template:
      spec:
        env:
          - name: "have-a-try"
            value: "whoo! It works"
  deletion_policy: "Delete"
